### ISSUE TITLE
Check if run start already in database

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/portable-mds#12]
While it seems that the runstop and descriptors error if they already exist, it seems that the run_starts don't do this.
Is that correct?
Is that desirable?

**Comment by tacaswell** [comment]
It should fail on inserting a duplicate.  I assume there is a 'unique' flag missing in setting up the table?

**Comment by arkilic** [comment]
Which part of portable-mds are you referring to? sqlite or json or hdf5 implementation?

**Comment by CJ-Wright** [comment]
sqlite

**Comment by danielballan** [comment]
Ported to https://github.com/NSLS-II/bluesky/issues/694
